# Generated by Django 4.1 on 2022-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('expire_date', models.DateField()),
                ('remind_day', models.IntegerField()),
                ('place', models.CharField(max_length=255)),
            ],
        ),
    ]
